# The command log.
#
# Every action that changes the session appends the *equivalent OITOOLS call* here, as text.
# Two things follow from that, and they are the reason the log exists rather than being a
# nicety:
#
#   1. GUI work becomes publishable. "Export script" writes a runnable .jl that reproduces
#      the session, so a figure made by clicking can be regenerated, diffed and cited.
#   2. It constrains the GUI. If an action cannot be written as an OITOOLS call, the GUI has
#      grown private logic that scripts cannot reproduce — and the export test will catch it.
#
# View state (zoom, colour-by, panel layout) is deliberately NOT logged: replaying it would
# not change any result, and it would bury the calls that do.

"""
    LogEntry(code; note = "")

One replayable step. `code` is Julia source, exactly as it would be typed; `note` is the
human-readable label shown in the log panel.

`binding` names the variable the step assigns to, when it assigns one, so later steps can
refer to it (`data1`, `model2`, …).
"""
struct LogEntry
    code    :: String
    note    :: String
    binding :: String
end
LogEntry(code::AbstractString; note::AbstractString = "", binding::AbstractString = "") =
    LogEntry(String(code), String(note), String(binding))

Base.show(io::IO, e::LogEntry) =
    print(io, isempty(e.note) ? e.code : "# " * e.note * "\n" * e.code)

"""
    log!(session, code; note = "", binding = "") -> String

Append a step to the session's command log and return `binding` (so callers can write
`name = log!(...)`). Called by every mutating action; not usually called directly.
"""
function log!(s, code::AbstractString; note::AbstractString = "", binding::AbstractString = "")
    push!(s.log, LogEntry(code; note = note, binding = binding))
    return binding
end

"""
    export_script(session; header = true) -> String

Render the command log as a runnable Julia script.

The result is exactly what the GUI did, in order, and running it must reproduce the session —
that round trip is the strongest test in the suite, because any divergence means the GUI has
private logic.
"""
function export_script(s; header::Bool = true)
    io = IOBuffer()
    if header
        println(io, "# Generated by OITOOLSGUI — reproduces this session.")
        println(io, "using OITOOLS")
        println(io)
    end
    for e in s.log
        isempty(e.note) || println(io, "# ", e.note)
        println(io, e.code)
        println(io)
    end
    return String(take!(io))
end

"""
    export_script(session, path) -> path

Write [`export_script`](@ref) to a file.
"""
function export_script(s, path::AbstractString; header::Bool = true)
    open(path, "w") do io
        write(io, export_script(s; header = header))
    end
    return path
end

"""
    _literal(x) -> String

Render a value as Julia source. Log lines must survive a round trip, so this has
to be exact rather than pretty: strings are escaped and quoted, floats keep full precision.
"""
_literal(x::AbstractString) = repr(String(x))
_literal(x::Symbol)         = ":" * String(x)
_literal(x::Bool)           = x ? "true" : "false"
_literal(x::Integer)        = string(x)
_literal(x::AbstractFloat)  = repr(x)          # full round-trip precision
_literal(x::Nothing)        = "nothing"
_literal(x::AbstractVector) = "[" * join(_literal.(x), ", ") * "]"
_literal(x::Tuple)          = "(" * join(_literal.(x), ", ") * ")"
function _literal(x::AbstractDict)
    isempty(x) && return "Dict()"
    inner = join(("$(_literal(k)) => $(_literal(v))" for (k, v) in sort(collect(x), by = first)), ", ")
    return "Dict(" * inner * ")"
end
_literal(x) = string(x)

"""
    _kwargs(pairs...) -> String

Render keyword arguments, skipping any whose value equals the OITOOLS default, so exported
scripts show what the user actually chose rather than every knob.
"""
function _kwargs(pairs::Vector{<:Pair}; defaults::AbstractDict = Dict())
    parts = String[]
    for (k, v) in pairs
        haskey(defaults, k) && isequal(defaults[k], v) && continue
        push!(parts, "$(k) = $(_literal(v))")
    end
    return join(parts, ", ")
end
