name = "SPICA"
int_trans = 1.0
vis = 0.80
n_pix_fringe = 600
n_pix_photometry = 4
flux_frac_photometry = 0.20
flux_frac_fringes = 0.80
throughput_photometry = 0.017
throughput_fringes = 0.066
n_splits = 6
read_noise = 0.1
quantum_efficiency = 0.80
v2_cal_err = 0.005
phase_cal_err = 1.0
incoh_int_time = 100.0
